#!/usr/bin/env node
"use strict";

var fs = require('fs');
var path = require('path');
var http = require('http');
var https = require('https');
var httpPort = 8080;
var httpsPort = 8443;  // Standard HTTPS port
var staticBasePath = './build';

var staticServe = function(req, res) {
    console.log("Request [" + req.url + "]") 
    // Make sure we're serving index.html for root path
    let filePath = req.url === '/' ? '/index.html' : req.url
    
    var resolvedBase = path.resolve(staticBasePath);
    var safeSuffix = path.normalize(filePath).replace(/^(\.\.[\/\\])+/, '');
    var fileLoc = path.join(resolvedBase, safeSuffix);
    
    fs.readFile(fileLoc, function(err, data) {
        if (err) {
            res.writeHead(404, 'Not Found');
            res.write('404: File Not Found!');
            return res.end();
        }
        
        res.statusCode = 200;

        res.write(data);
        return res.end();
    });
};

// Add SSL/TLS certificate configuration
var httpsOptions = {
    key: fs.readFileSync('certs/private.key'),
    cert: fs.readFileSync('certs/certificate.crt')
};

var httpServer = http.createServer(staticServe);
var httpsServer = https.createServer(httpsOptions, staticServe);

console.log("Start http server on port [" + httpPort + "]");
console.log("Start https server on port [" + httpsPort + "]");

httpServer.listen(httpPort);
httpsServer.listen(httpsPort);